package pl.krok.szymon.obiekty.pojazdy.enumy;

public enum Marka {
	TOYOTA, FORD, BMW, MERCEDES, AUDI, VOLKSWAGEN, HONDA, HYUNDAI, SUZUK, PORSHE, FIAT, LEXUS, DACIA, KIA, NISSAN, FERRARI, JEEP, LAND_ROVER, TESLA, MAZDA, SUBARU, OPEL;

}
